// Baza de date cu teste pentru printare (5 teste x 15 întrebări + Răspunsuri)

const printableTests = {
    "test_rep": {
        title: "Test Evaluare: Reguli de Reprezentare",
        chapter: "Desen de Ansamblu - Reguli Generale",
        questions: [
            "1. Definiți noțiunea de „desen de ansamblu” conform STAS.",
            "2. În ce poziție se reprezintă ansamblul în proiecția principală?",
            "3. Explicați regula hașurării a două piese adiacente.",
            "4. Cum se reprezintă șuruburile și piulițele în secțiune longitudinală?",
            "5. Care este rolul principal al unui desen de ansamblu?",
            "6. Enumerați trei tipuri de informații oferite de desenul de ansamblu.",
            "7. (Grilă) Numărul minim de proiecții necesar este: a) 3 b) 1 c) Cel minim necesar pentru claritate d) 6",
            "8. (Grilă) Ansamblurile mobile se reprezintă în poziția: a) De repaus b) Extremă c) De funcționare d) Oricare",
            "9. Ce tipuri de linii se folosesc pentru conturul aparent?",
            "10. Cum se reprezintă jocurile dintre piese?",
            "11. Explicați termenul de „secțiune frântă” în contextul desenului de ansamblu.",
            "12. Care este regula reprezentării elementelor identice care se repetă (ex: șuruburi)?",
            "13. Desenați schematic simbolul pentru o vedere parțială.",
            "14. (Grilă) Hașurile se trasează la un unghi de: a) 30° b) 45° c) 60° d) 90°",
            "15. Ce reprezintă o vedere locală?"
        ],
        answers: [
            "1. Reprezentarea grafică a unui grup de piese asamblate care funcționează împreună.",
            "2. În poziția de funcționare.",
            "3. Se hașurează în direcții diferite sau cu pași diferiți.",
            "4. Nu se hașurează (se reprezintă pline).",
            "5. Înțelegerea funcționării și a modului de asamblare.",
            "6. Forma pieselor, poziția relativă, dimensiuni de montaj/gabarit.",
            "7. c) Cel minim necesar pentru claritate.",
            "8. c) De funcționare (sau poziții extreme reprezentate cu linie punctată).",
            "9. Linii continue groase.",
            "10. Prin reprezentarea liniilor de contur distincte pentru fiecare piesă.",
            "11. O secțiune formată din mai multe plane secante paralele.",
            "12. Se reprezintă complet unul singur, restul prin axe sau contur simplificat.",
            "13. (Desen schematic cu linie de ruptură)",
            "14. b) 45°.",
            "15. Reprezentarea unei părți limitate a obiectului."
        ]
    },
    "test_poz": {
        title: "Test Evaluare: Poziționarea Pieselor",
        chapter: "Identificarea și Numerotarea Componentelor",
        questions: [
            "1. Ce element grafic se folosește pentru identificarea pieselor pe desen?",
            "2. Unde se amplasează numerele de poziție (baloanele)?",
            "3. Care este regula privind intersecția liniilor de indicație?",
            "4. Cum se termină linia de indicație pe suprafața unei piese?",
            "5. Cum se termină linia de indicație pe muchia unei piese?",
            "6. (Grilă) Mărimea cifrelor de poziție față de cotele normale este: a) Egală b) Mai mică c) De 1.5-2 ori mai mare",
            "7. În ce ordine se numerotează piesele de obicei?",
            "8. (Grilă) Se poate repeta același număr de poziție pe desen? a) Da, oriunde b) Nu, o singură dată c) Doar dacă e necesar pentru claritate",
            "9. Cum se poziționează un grup de elemente de fixare (șurub+șaibă+piuliță)?",
            "10. Ce regulă se aplică alinierii baloanelor de poziție?",
            "11. Pot fi scrise numerele de poziție în interiorul conturului pieselor?",
            "12. Cum se leagă numărul de poziție de tabelul de componență?",
            "13. Desenați un exemplu corect de linie de indicație pentru o suprafață.",
            "14. Ce excepții există de la regulaalinierii numerelor?",
            "15. Explicați rolul punctului îngroșat de la capătul liniei de indicație."
        ],
        answers: [
            "1. Linia de indicație și numărul de poziție (balonul).",
            "2. În afara conturului proiecțiilor.",
            "3. Liniile de indicație NU trebuie să se intersecteze.",
            "4. Cu un punct îngroșat.",
            "5. Cu o săgeată.",
            "6. c) De 1.5-2 ori mai mare.",
            "7. În sensul acelor de ceasornic sau în ordinea montajului.",
            "8. b) Nu, o singură dată (de regulă).",
            "9. Printr-o singură linie de indicație ramificată sau comună.",
            "10. Se aliniază pe orizontală sau verticală (paralel cu chenarul).",
            "11. Nu, doar în cazuri excepționale când nu există spațiu.",
            "12. Prin numărul crt. din tabel care corespunde cu numărul de pe desen.",
            "13. (Desen: punct pe piesă, linie dreaptă, număr în afară)",
            "14. Când aglomerarea nu permite, se decalatează ușor, dar tot ordonat.",
            "15. Indică clar piesa la care se referă poziția."
        ]
    },
    "test_cot": {
        title: "Test Evaluare: Cotarea Ansamblului",
        chapter: "Reguli de Cotare",
        questions: [
            "1. Enumerați cele 4 categorii principale de cote pe un desen de ansamblu.",
            "2. Ce reprezintă cotele de gabarit?",
            "3. Dați două exemple de cote de legătură.",
            "4. De ce nu se cotează detaliat toate piesele pe desenul de ansamblu?",
            "5. Ce sunt cotele funcționale?",
            "6. (Grilă) Cota care indică distanța dintre șuruburile de prindere pe fundație este cotă de: a) Gabarit b) Legătură c) Montaj",
            "7. Cum se cotează un ansamblu cu piese mobile (ex: piston)?",
            "8. Ce informații oferă cotele de montaj?",
            "9. (Grilă) Toleranțele și ajustajele se înscriu: a) În tabel b) Pe desen, lângă cota nominală c) Nu se înscriu",
            "10. Care este rolul cotelor tehnologice de prelucrare comună?",
            "11. Dați un exemplu de ajustaj care trebuie cotat pe ansamblu.",
            "12. Cum se cotează diametrul unei flanșe de cuplare?",
            "13. Explicați diferența dintre o cotă funcțională și una de gabarit.",
            "14. Ce unitate de măsură se folosește implicit în desenul tehnic industrial?",
            "15. Când este permisă cotarea elementelor componente individuale pe ansamblu?"
        ],
        answers: [
            "1. Gabarit, Legătură, Montaj, Funcționale.",
            "2. Dimensiunile maxime exterioare (L x l x h).",
            "3. Diametrul flanșei, distanța între găuri de prindere.",
            "4. Deoarece acelea se găsesc pe desenele de execuție individuale.",
            "5. Cote care definesc performanța sau funcționarea (ex: curse, debite prin diametre).",
            "6. b) Legătură.",
            "7. Se cotează pozițiile extreme (minimă și maximă).",
            "8. Distanțe necesare pentru reglaje în timpul asamblării.",
            "9. b) Pe desen, lângă cota nominală (ex: H7/g6).",
            "10. Indică prelucrări care se fac DUPĂ asamblare (ex: alezare comună).",
            "11. Ajustajul dintre arbore și lagăr (ex: Ø40 H7/f7).",
            "12. Ca o cotă de legătură sau gabarit, cu simbolul Ø.",
            "13. Funcționala asigură funcționarea; Gabaritul definește volumul ocupat.",
            "14. Milimetrul (mm).",
            "15. Doar dacă piesa este foarte simplă și nu are desen separat."
        ]
    },
    "test_mat": {
        title: "Test Evaluare: Materiale",
        chapter: "Notarea și Simbolizarea Materialelor",
        questions: [
            "1. Ce semnifică simbolul OL în vechiul standard românesc?",
            "2. Care este echivalentul european (SR EN) pentru OL 37?",
            "3. Pentru ce tipuri de piese se folosește OLC 45?",
            "4. Ce reprezintă numărul '200' din simbolul Fc 200?",
            "5. Enumerați două proprietăți ale fontei cenușii.",
            "6. (Grilă) Bronzul se utilizează frecvent pentru: a) Carcase b) Lagăre și bucșe c) Șuruburi",
            "7. Ce material este indicat pentru un arbore puternic solicitat?",
            "8. Ce înseamnă simbolul S235JR?",
            "9. Care este diferența dintre oțel și fontă (procent de carbon)?",
            "10. Cum se notează alama în desenele tehnice?",
            "11. (Grilă) Un șurub de înaltă rezistență (Gr. 8.8) este din: a) Fontă b) Oțel aliat c) Aluminiu",
            "12. Pentru ce se folosește aluminiul în construcția de mașini?",
            "13. Ce tratament termic se aplică uzual oțelului OLC 45?",
            "14. Explicați termenul de 'oțel laminat'.",
            "15. Ce material ați alege pentru batiul unei mașini unelte grele și de ce?"
        ],
        answers: [
            "1. Oțel Laminat.",
            "2. S235.",
            "3. Arbori, roți dințate, piese solicitate mediu.",
            "4. Rezistența minimă la rupere (200 N/mm²).",
            "5. Turnabilitate bună, amortizarea vibrațiilor.",
            "6. b) Lagăre și bucșe.",
            "7. Oțel Aliat (ex: 41MoCr11) sau OLC superior tratat.",
            "8. S = Structural, 235 = Limita de curgere, JR = Clasa de calitate.",
            "9. Oțel < 2.11% C, Fontă > 2.11% C.",
            "10. Cu simbolul chimic Cu-Zn sau denumirea comercială (Am).",
            "11. b) Oțel aliat.",
            "12. Piese ușoare, carcase, pistoane.",
            "13. Îmbunătățire (Călire + Revenire înaltă).",
            "14. Oțel tras prin valțuri (laminor) pentru a obține profile.",
            "15. Fontă, pentru că amortizează vibrațiile mașinii."
        ]
    },
    "test_tab": {
        title: "Test Evaluare: Tabel Componență",
        chapter: "Structura Tabelului de Componență",
        questions: [
            "1. Unde se amplasează tabelul de componență pe planșă?",
            "2. Care sunt coloanele obligatorii ale unui tabel de componență?",
            "3. În ce ordine se completează tabelul (sus-jos sau jos-sus)?",
            "4. Ce informații se trec în coloana 'Observații'?",
            "5. Cum se leagă tabelul de desenul propriu-zis?",
            "6. (Grilă) Dacă tabelul nu încape deasupra indicatorului, se poate continua: a) Pe verso b) În stânga indicatorului c) Pe altă planșă",
            "7. Ce se trece în coloana 'Standard / Nr. Desen' pentru un șurub?",
            "8. Cum se completează rubrica 'Material' pentru un subansamblu?",
            "9. (Grilă) Titlurile coloanelor se scriu: a) Jos b) Sus c) La mijloc",
            "10. Explicați rolul coloanei 'Bucăți' (Cantitate).",
            "11. Poate tabelul de componență să fie o pagină A4 separată?",
            "12. Ce se întâmplă cu tabelul dacă desenul are mai multe planșe?",
            "13. Cum se evidențiază piesele standardizate în tabel?",
            "14. Ce dimensiune trebuie să aibă liniile tabelului de componență?",
            "15. Realizați o schiță a capului de tabel (antetului)."
        ],
        answers: [
            "1. Deasupra indicatorului, în colțul din dreapta jos.",
            "2. Poz., Denumire, Nr. Desen/STAS, Material, Buc, Obs.",
            "3. De jos în sus (de obicei) sau de sus în jos (conform ISO modern).",
            "4. Masa netă, observații speciale, furnizor.",
            "5. Prin numerele de poziție (Poz).",
            "6. b) În stânga indicatorului (sau pe altă planșă A4).",
            "7. Standardul respectiv (ex: ISO 4014).",
            "8. Nu se completează (se pune linie) sau se scrie ansamblu.",
            "9. a) Jos (la baza tabelului) pentru completare inversă sau Sus.",
            "10. Indică numărul necesar din acea piesă pentru UN ansamblu.",
            "11. Da, conform standardelor noi.",
            "12. Se pune pe prima planșă sau separat.",
            "13. Prin numele standardului în locul numărului de desen.",
            "14. Contur gros, linii interioare subțiri.",
            "15. (Schiță cu coloanele specificate)"
        ]
    }
};
